import { v } from "convex/values";
import { mutationGeneric as mutation, queryGeneric as query } from "convex/server";

import { requireCurrentUser } from "./lib/auth";

export const searchCatalog = query({ args: { query: v.string(), locale: v.string() }, handler: async (ctx, args) => { await requireCurrentUser(ctx); const normalized = args.query.trim().toLocaleLowerCase(); const foods = await ctx.db.query("foodCatalog").withIndex("by_active", (q) => q.eq("active", true)).take(100); return foods.filter((food) => (Object.values(food.titles) as string[]).some((title) => title.toLocaleLowerCase().includes(normalized))).slice(0, 30); } });
export const getRecommendations = query({ args: { goalType: v.union(v.literal("lose"), v.literal("maintain"), v.literal("gain")) }, handler: async (ctx, args) => { await requireCurrentUser(ctx); const foods = await ctx.db.query("foodCatalog").withIndex("by_active", (q) => q.eq("active", true)).take(100); return foods.filter((food) => food.goalTypes.includes(args.goalType)); } });
export const getFavorites = query({ args: {}, handler: async (ctx) => { const user = await requireCurrentUser(ctx); return ctx.db.query("favorites").withIndex("by_user", (q) => q.eq("userId", user._id)).collect(); } });
export const getRecent = query({ args: { limit: v.optional(v.number()) }, handler: async (ctx, args) => { const user = await requireCurrentUser(ctx); const logs = await ctx.db.query("foodLogs").withIndex("by_user_created", (q) => q.eq("userId", user._id)).order("desc").take(Math.min(args.limit ?? 20, 50)); const seen = new Set<string>(); return logs.filter((log) => { const key = `${log.foodName}:${log.serving}:${log.servingUnit}`; if (seen.has(key)) return false; seen.add(key); return true; }); } });
export const toggleFavorite = mutation({ args: { referenceType: v.union(v.literal("catalog"), v.literal("custom")), referenceId: v.string() }, handler: async (ctx, args) => { const user = await requireCurrentUser(ctx); const existing = await ctx.db.query("favorites").withIndex("by_user_reference", (q) => q.eq("userId", user._id)).filter((q) => q.eq(q.field("referenceId"), args.referenceId)).unique(); if (existing) { await ctx.db.delete(existing._id); return false; } await ctx.db.insert("favorites", { userId: user._id, ...args, createdAt: Date.now() }); return true; } });
