import { ConvexError, v } from "convex/values";
import { mutationGeneric as mutation, queryGeneric as query } from "convex/server";

import { requireCurrentUser } from "./lib/auth";

export const getHistory = query({ args: { limit: v.optional(v.number()) }, handler: async (ctx, args) => { const user = await requireCurrentUser(ctx); return ctx.db.query("weightLogs").withIndex("by_user_date", (q) => q.eq("userId", user._id)).order("desc").take(Math.min(args.limit ?? 100, 500)); } });
export const getProgress = query({ args: {}, handler: async (ctx) => { const user = await requireCurrentUser(ctx); const profile = await ctx.db.query("userProfiles").withIndex("by_user", (q) => q.eq("userId", user._id)).unique(); const logs = await ctx.db.query("weightLogs").withIndex("by_user_date", (q) => q.eq("userId", user._id)).order("asc").collect(); return { profile, first: logs[0] ?? null, latest: logs.at(-1) ?? null, count: logs.length }; } });
export const create = mutation({ args: { normalizedKg: v.number(), displayValue: v.number(), displayUnit: v.union(v.literal("kg"), v.literal("lb")), localDate: v.string(), timezone: v.string(), note: v.optional(v.string()), clientRequestId: v.string() }, handler: async (ctx, args) => { const user = await requireCurrentUser(ctx); if (args.normalizedKg < 35 || args.normalizedKg > 350) throw new ConvexError("Weight is outside the supported range"); const existing = await ctx.db.query("weightLogs").withIndex("by_user_request", (q) => q.eq("userId", user._id)).filter((q) => q.eq(q.field("clientRequestId"), args.clientRequestId)).unique(); if (existing) return existing._id; const now = Date.now(); return ctx.db.insert("weightLogs", { userId: user._id, ...args, createdAt: now, updatedAt: now }); } });
export const remove = mutation({ args: { id: v.id("weightLogs") }, handler: async (ctx, { id }) => { const user = await requireCurrentUser(ctx); const record = await ctx.db.get(id); if (!record || record.userId !== user._id) throw new ConvexError("Weight entry not found"); await ctx.db.delete(id); } });
