/// <reference types="react-native-css/types" />

// Generated by react-native-css. Keep this file committed for className typings.

/**
 * Side-effect stylesheet imports (`import "@/global.css"`). Metro resolves these
 * through the NativeWind transformer; TypeScript needs the ambient declaration.
 */
declare module "*.css" {
  const content: string;
  export default content;
}
